# vim: filetype=python

## load our own python modules
import utils.system as system
from utils.build_tools import find_files_recursive

import os

# import build env
Import('env')
local_env = env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'shaders', 'src')
source_files  = find_files_recursive(src_base_dir, ['.c', '.cpp'])
include_files = find_files_recursive(src_base_dir, ['.h'])

if system.os == 'windows' and local_env['MODE'] == 'opt':
    MSVC_FLAGS = " /Zi"
    MSVC_FLAGS += " /FS"
    MSVC_FLAGS += " /Fd"+local_env['BUILD_BASE_DIR']+"\\mtoa_shaders_tmp.pdb"
    local_env.Append(CCFLAGS = Split(MSVC_FLAGS))
local_env.Append(CPPPATH = ['.'])

if system.os =='windows':
    local_env.Append(LIBS=Split('ai.lib ws2_32.lib'))
else:    
    local_env.Append(LIBS=Split('ai'))
    local_env.Append(CCFLAGS = Split('-fvisibility=hidden')) # hide symbols by default

MTOA_SHADERS = local_env.SharedLibrary('mtoa_shaders', source_files, LIBPREFIX='')

Return('MTOA_SHADERS')
