#pragma once

#define MTOA_VAL(str) #str
#define MTOA_TOSTRING(str) MTOA_VAL(str)

#define MTOA_VENDOR "Solid Angle SL"
#define MTOA_ARCH_VERSION_NUM 3
#define MTOA_MAJOR_VERSION_NUM 3
#define MTOA_MINOR_VERSION_NUM 0
// #define MTOA_FIX_VERSION "rc2"


#define MTOA_ARCH_VERSION         MTOA_TOSTRING(MTOA_ARCH_VERSION_NUM)
#define MTOA_MAJOR_VERSION         MTOA_TOSTRING(MTOA_MAJOR_VERSION_NUM)
#define MTOA_MINOR_VERSION         MTOA_TOSTRING(MTOA_MINOR_VERSION_NUM)

#ifdef MTOA_FIX_VERSION
#define MTOA_VERSION MTOA_ARCH_VERSION "." MTOA_MAJOR_VERSION "." MTOA_MINOR_VERSION "." MTOA_FIX_VERSION
#else
#define MTOA_VERSION MTOA_ARCH_VERSION "." MTOA_MAJOR_VERSION "." MTOA_MINOR_VERSION
#endif 

#ifndef MAYA_VERSION
   #define MAYA_VERSION "Any"
#endif
