#ifndef VERSION_H
#define VERSION_H

#define MTOA_VAL(str) #str
#define MTOA_TOSTRING(str) MTOA_VAL(str)

#define MTOA_VENDOR "SolidAngle"
#define MTOA_MAJOR_VERSION_NUM 0
#define MTOA_MINOR_VERSION_NUM 19
#define MTOA_FIX_VERSION "0.dev"


#define MTOA_MAJOR_VERSION         MTOA_TOSTRING(MTOA_MAJOR_VERSION_NUM)
#define MTOA_MINOR_VERSION         MTOA_TOSTRING(MTOA_MINOR_VERSION_NUM)

#define MTOA_VERSION MTOA_MAJOR_VERSION "." MTOA_MINOR_VERSION "." MTOA_FIX_VERSION

#ifndef MAYA_VERSION
   #define MAYA_VERSION "Any"
#endif

#endif // VERSION_H
