import system, os

Import('proc_env')

src_base_dir  = os.path.join(proc_env['ROOT_DIR'], 'procedurals', 'xgen')
include_files = [os.path.join(src_base_dir, 'XgArnoldProcedural.h')]
source_files  = [os.path.join(src_base_dir, 'XgArnoldProcedural.cpp')]

proc_env.Append(CPPPATH = [os.path.join(proc_env['MAYA_ROOT'], 'include')])
proc_env.Append(CPPPATH = [os.path.join(proc_env['MAYA_ROOT'], 'plug-ins', 'xgen', 'include')])
proc_env.Append(CPPPATH = [os.path.join(proc_env['MAYA_ROOT'], 'plug-ins', 'xgen', 'include', 'xgen')])
proc_env.Append(LIBPATH = [os.path.join(proc_env['MAYA_ROOT'], 'plug-ins', 'xgen', 'lib')])

if system.os() =='windows':
   proc_env.Append(CPPPATH = ['.'])   
   proc_env.Append(LIBS=Split('ai.lib'))
   proc_env.Append(LIBS=Split('libAdskSeExpr.lib'))
   proc_env.Append(LIBS=Split('libAdskXGen.lib'))
else:
   proc_env.Append(CPPPATH = ['.'])
   proc_env.Append(LIBS=Split('ai'))
   proc_env.Append(LIBS=Split('AdskSeExpr'))
   proc_env.Append(LIBS=Split('AdskXGen'))
   proc_env.Append(CCFLAGS = Split('-fvisibility=hidden')) # hide symbols by default

MTOA_PROCS = proc_env.SharedLibrary('xgen_procedural', source_files, LIBPREFIX='')

Return('MTOA_PROCS')
