import maya.cmds as cmds
import maya.mel as mel
import mtoa.ui.ae.customShapeAttributes as customShapeAttributes
from mtoa.ui.ae.aiSwatchDisplay import aiSwatchDisplay

def aiAreaLightTemplate(nodeName):

    aiSwatchDisplay(nodeName)

    cmds.editorTemplate(beginScrollLayout=True)

    cmds.editorTemplate(beginLayout="Area Light Attributes", collapse=False)

    cmds.editorTemplate("type", addControl=True, label="Type")
    cmds.editorTemplate("color", addControl=True, label="Color")
    cmds.editorTemplate("intensity", addControl=True, label="Intensity")
    cmds.editorTemplate(beginNoOptimize=True)
    cmds.editorTemplate("emitDiffuse", addControl=True, label="Emit Diffuse")
    cmds.editorTemplate("emitSpecular",addControl=True, label="Emit Specular")
    cmds.editorTemplate(endNoOptimize=True)
    
    cmds.editorTemplate(addSeparator=True)
    
    cmds.editorTemplate("aiCastShadows", addControl=True, label="Cast Shadows")
    cmds.editorTemplate("aiExposure", addControl=True, label="Exposure")
    cmds.editorTemplate("aiSamples", addControl=True, label="Samples")
    cmds.editorTemplate("aiMis", addControl=True, label="Multiple Importance Sampling")
    
    cmds.editorTemplate(addSeparator=True)
    
    cmds.editorTemplate("aiResolution", addControl=True, label="Resolution")
    cmds.editorTemplate("aiAffectVolumetrics", addControl=True, label="Affect Volumetrics")
    cmds.editorTemplate("aiCastVolumetricShadows", addControl=True, label="Cast Volumetric Shadows")

    cmds.editorTemplate(addSeparator=True)

    cmds.editorTemplate("aiNormalize", addControl=True, label="Normalize")
    cmds.editorTemplate("aiBounceFactor", addControl=True, label="Bounce Factor")
    cmds.editorTemplate("aiBounces", addControl=True, label="Bounces")
    cmds.editorTemplate("aiSssSamples", addControl=True, label="SSS Samples")
    
    cmds.editorTemplate(endLayout=True)
    
    cmds.editorTemplate(beginLayout="Light Filters", collapse=False)
    #self.addCustom("aiFilters", self.customLightFiltersNew, self.customLightFiltersReplace)
    cmds.editorTemplate(endLayout=True)

    # include/call base class/node attributes
    mel.eval('AEdependNodeTemplate "%s"' % nodeName)
    cmds.editorTemplate(suppress="blackBox")
    cmds.editorTemplate(suppress="containerType")
    cmds.editorTemplate(suppress="templateName")
    cmds.editorTemplate(suppress="viewName")
    cmds.editorTemplate(suppress="iconName")
    cmds.editorTemplate(suppress="templateVersion")
    cmds.editorTemplate(suppress="uiTreatment")
    cmds.editorTemplate(suppress="customTreatment")
    cmds.editorTemplate(suppress="creator")
    cmds.editorTemplate(suppress="creationDate")
    cmds.editorTemplate(suppress="rmbCommand")
    cmds.editorTemplate(suppress="templatePath")
    cmds.editorTemplate(suppress="viewMode")
    cmds.editorTemplate(suppress="ignoreHwShader")
    cmds.editorTemplate(suppress="boundingBoxScale")
    cmds.editorTemplate(suppress="featureDisplacement")
    cmds.editorTemplate(suppress="boundingBoxScale")
    cmds.editorTemplate(suppress="initialSampleRate")
    cmds.editorTemplate(suppress="extraSampleRate")
    cmds.editorTemplate(suppress="textureThreshold")
    cmds.editorTemplate(suppress="normalThreshold")
    cmds.editorTemplate(suppress="lodVisibility")
    cmds.editorTemplate(suppress="ghostingControl")
    cmds.editorTemplate(suppress="ghostPreSteps")
    cmds.editorTemplate(suppress="ghostPostSteps")
    cmds.editorTemplate(suppress="ghostStepSize")
    cmds.editorTemplate(suppress="ghostRangeStart")
    cmds.editorTemplate(suppress="ghostRangeEnd")
    cmds.editorTemplate(suppress="ghostDriver")
    cmds.editorTemplate(suppress="ghostFrames")
    cmds.editorTemplate(suppress="ghosting")
    cmds.editorTemplate(suppress="ghostCustomSteps")
    cmds.editorTemplate(suppress="tweak")
    cmds.editorTemplate(suppress="relativeTweak")
    cmds.editorTemplate(suppress="currentUVSet")
    cmds.editorTemplate(suppress="displayImmediate")
    cmds.editorTemplate(suppress="displayColors")
    cmds.editorTemplate(suppress="displayColorChannel")
    cmds.editorTemplate(suppress="currentColorSet")
    cmds.editorTemplate(suppress="smoothShading")
    cmds.editorTemplate(suppress="drawOverride")
    cmds.editorTemplate(suppress="shadingSamples")
    cmds.editorTemplate(suppress="maxVisibilitySamplesOverride")
    cmds.editorTemplate(suppress="maxVisibilitySamples")
    cmds.editorTemplate(suppress="antialiasingLevel")
    cmds.editorTemplate(suppress="maxShadingSamples")
    cmds.editorTemplate(suppress="shadingSamplesOverride")
    cmds.editorTemplate(suppress="geometryAntialiasingOverride")
    cmds.editorTemplate(suppress="antialiasingLevel")
    cmds.editorTemplate(suppress="volumeSamplesOverride")
    cmds.editorTemplate(suppress="volumeSamples")
    cmds.editorTemplate(suppress="depthJitter")
    cmds.editorTemplate(suppress="ignoreSelfShadowing")
    cmds.editorTemplate(suppress="controlPoints")
    cmds.editorTemplate(suppress="colorSet")
    cmds.editorTemplate(suppress="uvSet")
    cmds.editorTemplate(suppress="weights")
    cmds.editorTemplate(suppress="renderInfo")
    cmds.editorTemplate(suppress="renderLayerInfo")
    cmds.editorTemplate(suppress="compInstObjGroups")
    cmds.editorTemplate(suppress="instObjGroups")
    cmds.editorTemplate(suppress="collisionOffsetVelocityIncrement")
    cmds.editorTemplate(suppress="collisionOffsetVelocityMultiplier")
    cmds.editorTemplate(suppress="collisionDepthVelocityMultiplier")
    cmds.editorTemplate(suppress="collisionDepthVelocityIncrement")
    cmds.editorTemplate(suppress="visibility")
    cmds.editorTemplate(suppress="intermediateObject")
    cmds.editorTemplate(suppress="template")
    cmds.editorTemplate(suppress="useObjectColor")
    cmds.editorTemplate(suppress="objectColor")
    cmds.editorTemplate(suppress="motionBlur")
    cmds.editorTemplate(suppress="visibleInReflections")
    cmds.editorTemplate(suppress="visibleInRefractions")
    cmds.editorTemplate(suppress="castsShadows")
    cmds.editorTemplate(suppress="receiveShadows")
    cmds.editorTemplate(suppress="primaryVisibility")
    cmds.editorTemplate(suppress="localPosition")
    cmds.editorTemplate(suppress="localScale")
    cmds.editorTemplate(suppress="normalCamera")
    cmds.editorTemplate(suppress="pointCamera")
    
    cmds.editorTemplate(addExtraControls=True)
    cmds.editorTemplate(endScrollLayout=True)
