import maya.cmds as cmds
import maya.mel as mel

def ArnoldStandInTemplate(nodeName):

    cmds.editorTemplate(beginScrollLayout=True)

    cmds.editorTemplate(beginLayout="Standin Attributes", collapse=False)

    cmds.editorTemplate("dso", addControl=True)
    cmds.editorTemplate("data", addControl=True)

    cmds.editorTemplate(endLayout=True)
    
    cmds.editorTemplate(beginLayout="Ass Reader Attributes", collapse=False)
    
    cmds.editorTemplate("useFrameExtension", addControl=True)
    cmds.editorTemplate("frameNumber", addControl=True)
    cmds.editorTemplate("frameOffset", addControl=True)
    cmds.editorTemplate("mode", addControl=True)
    cmds.editorTemplate(endLayout=True)
    
    cmds.editorTemplate(beginLayout="Visibility", collapse=False)
    cmds.editorTemplate("opaque", addControl=True)
    cmds.editorTemplate("primaryVisibility", addControl=True)
    cmds.editorTemplate("castsShadows", addControl=True)
    cmds.editorTemplate("receiveShadows", addControl=True)
    cmds.editorTemplate("selfShadows", addControl=True)
    cmds.editorTemplate("visibleInReflections", addControl=True)
    cmds.editorTemplate("visibleInRefractions", addControl=True)
    cmds.editorTemplate("visibleInDiffuse", addControl=True)
    cmds.editorTemplate("visibleInGlossy", addControl=True)
    cmds.editorTemplate("motionBlur", addControl=True)
    cmds.editorTemplate("doubleSided", addControl=True)
    cmds.editorTemplate("opposite", addControl=True)
    cmds.editorTemplate(endLayout=True)


    cmds.editorTemplate(endLayout=True)

    cmds.editorTemplate(beginLayout="Standin Bounding Box", collapse=False)
    cmds.editorTemplate("loadAtInit", addControl=True)
    cmds.editorTemplate("MinBoundingBox", addControl=True)
    cmds.editorTemplate("MaxBoundingBox", addControl=True)
    cmds.editorTemplate(endLayout=True) 

    cmds.editorTemplate(beginLayout="Object Display", collapse=True)
    cmds.editorTemplate("visibility", addControl=True)
    cmds.editorTemplate("template", addControl=True)
    cmds.editorTemplate("ghosting", addControl=True)
    cmds.editorTemplate("intermediateObject", addControl=True)
    cmds.editorTemplate(endLayout=True)

    cmds.editorTemplate(beginLayout="Draw Override", collapse=True)
    cmds.editorTemplate("overrideDisplayType", addControl=True)
    cmds.editorTemplate("overrideLevelOfDetail", addControl=True)
    cmds.editorTemplate("overrideShading", addControl=True)
    cmds.editorTemplate("overrideTexturing", addControl=True)
    cmds.editorTemplate("overridePlayback", addControl=True)
    cmds.editorTemplate("overrideEnabled", addControl=True)
    cmds.editorTemplate("useObjectColor", addControl=True)
    cmds.editorTemplate("objectColor", addControl=True)
    cmds.editorTemplate(endLayout=True)    


    # include/call base class/node attributes
    mel.eval('AEdependNodeTemplate "%s"' % nodeName)
    cmds.editorTemplate(suppress="blackBox")
    cmds.editorTemplate(suppress="containerType")
    cmds.editorTemplate(suppress="templateName")
    cmds.editorTemplate(suppress="viewName")
    cmds.editorTemplate(suppress="iconName")
    cmds.editorTemplate(suppress="templateVersion")
    cmds.editorTemplate(suppress="uiTreatment")
    cmds.editorTemplate(suppress="customTreatment")
    cmds.editorTemplate(suppress="creator")
    cmds.editorTemplate(suppress="creationDate")
    cmds.editorTemplate(suppress="rmbCommand")
    cmds.editorTemplate(suppress="templatePath")
    cmds.editorTemplate(suppress="viewMode")
    cmds.editorTemplate(suppress="ignoreHwShader")
    cmds.editorTemplate(suppress="boundingBoxScale")
    cmds.editorTemplate(suppress="featureDisplacement")
    cmds.editorTemplate(suppress="boundingBoxScale")
    cmds.editorTemplate(suppress="initialSampleRate")
    cmds.editorTemplate(suppress="extraSampleRate")
    cmds.editorTemplate(suppress="textureThreshold")
    cmds.editorTemplate(suppress="normalThreshold")
    cmds.editorTemplate(suppress="lodVisibility")
    cmds.editorTemplate(suppress="ghostingControl")
    cmds.editorTemplate(suppress="ghostPreSteps")
    cmds.editorTemplate(suppress="ghostPostSteps")
    cmds.editorTemplate(suppress="ghostStepSize")
    cmds.editorTemplate(suppress="ghostRangeStart")
    cmds.editorTemplate(suppress="ghostRangeEnd")
    cmds.editorTemplate(suppress="ghostDriver")
    cmds.editorTemplate(suppress="ghostFrames")
    cmds.editorTemplate(suppress="ghosting")
    cmds.editorTemplate(suppress="ghostCustomSteps")
    cmds.editorTemplate(suppress="tweak")
    cmds.editorTemplate(suppress="relativeTweak")
    cmds.editorTemplate(suppress="currentUVSet")
    cmds.editorTemplate(suppress="displayImmediate")
    cmds.editorTemplate(suppress="displayColors")
    cmds.editorTemplate(suppress="displayColorChannel")
    cmds.editorTemplate(suppress="currentColorSet")
    cmds.editorTemplate(suppress="smoothShading")
    cmds.editorTemplate(suppress="drawOverride")
    cmds.editorTemplate(suppress="shadingSamples")
    cmds.editorTemplate(suppress="maxVisibilitySamplesOverride")
    cmds.editorTemplate(suppress="maxVisibilitySamples")
    cmds.editorTemplate(suppress="antialiasingLevel")
    cmds.editorTemplate(suppress="maxShadingSamples")
    cmds.editorTemplate(suppress="shadingSamplesOverride")
    cmds.editorTemplate(suppress="geometryAntialiasingOverride")
    cmds.editorTemplate(suppress="antialiasingLevel")
    cmds.editorTemplate(suppress="volumeSamplesOverride")
    cmds.editorTemplate(suppress="volumeSamples")
    cmds.editorTemplate(suppress="depthJitter")
    cmds.editorTemplate(suppress="ignoreSelfShadowing")
    cmds.editorTemplate(suppress="controlPoints")
    cmds.editorTemplate(suppress="colorSet")
    cmds.editorTemplate(suppress="uvSet")
    cmds.editorTemplate(suppress="weights")
    cmds.editorTemplate(suppress="renderInfo")
    cmds.editorTemplate(suppress="renderLayerInfo")
    cmds.editorTemplate(suppress="compInstObjGroups")
    cmds.editorTemplate(suppress="instObjGroups")
    cmds.editorTemplate(suppress="collisionOffsetVelocityIncrement")
    cmds.editorTemplate(suppress="collisionOffsetVelocityMultiplier")
    cmds.editorTemplate(suppress="collisionDepthVelocityMultiplier")
    cmds.editorTemplate(suppress="collisionDepthVelocityIncrement")
    
    cmds.editorTemplate(addExtraControls=True)
    cmds.editorTemplate(endScrollLayout=True)