// Comment:  For now we can't "un-hide" a light that was originally hidden, 
// because it needs to go through a Maya "idle" process and I can't make this work by script so far

arnoldRenderView -mode "render_silent";
pause -sec 1;
//======== Hide the area light

setAttr "aiAreaLight1.visibility" 0;
setAttr "aiAreaLightShape1.intensity" 1;
pause -sec 1;

string $img = `pwd`;
$img += "/testrender_1.tif";
arnoldRenderView -option "Save Image" $img;

//========= hide the point light
setAttr "pointLight1.visibility" 0;
setAttr "pointLightShape1.intensity" 1;
pause -sec 1;
$img = `pwd`;
$img += "/testrender_2.tif";
arnoldRenderView -option "Save Image" $img;

//========== hide the skydome
setAttr "aiSkyDomeLight1.visibility" 0;
setAttr "aiSkyDomeLightShape1.intensity" 1;
pause -sec 1;
$img = `pwd`;
$img += "/testrender_3.tif";
arnoldRenderView -option "Save Image" $img;

//========= Un-hide the point light
setAttr "pointLight1.visibility" 1;
setAttr "pointLightShape1.intensity" 1;
pause -sec 1;
$img = `pwd`;
$img += "/testrender_4.tif";
arnoldRenderView -option "Save Image" $img;


//========== hide the directional light
setAttr "directionalLight1.visibility" 0;
setAttr "directionalLightShape1.intensity" 1;
pause -sec 1;
$img = `pwd`;
$img += "/testrender_5.tif";
arnoldRenderView -option "Save Image" $img;

//========== unhide the skydome
setAttr "aiSkyDomeLight1.visibility" 1;
setAttr "aiSkyDomeLightShape1.intensity" 1;
pause -sec 1;
$img = `pwd`;
$img += "/testrender_6.tif";
arnoldRenderView -option "Save Image" $img;
