arnoldRenderView -mode "render_silent";
pause -sec 1;
arnoldRenderView -option "Wait Render"  "1";
string $img = "";

//======== Set the subdivision to catclark

setAttr "pCubeShape1.aiSubdivType" 1;
setAttr "pCube1.inheritsTransform" 1;
pause -sec 1;
arnoldRenderView -option "Wait Render"  "1";

$img = `pwd`;
$img += "/testrender_1.tif";
arnoldRenderView -option "Save Image" $img;

//======== Increase the subdivision steps

setAttr "pCubeShape1.aiSubdivIterations" 2;
setAttr "pCube1.inheritsTransform" 1;
pause -sec 1;
arnoldRenderView -option "Wait Render"  "1";

$img = `pwd`;
$img += "/testrender_2.tif";
arnoldRenderView -option "Save Image" $img;

//======== Set the subdivision to linear

setAttr "pCubeShape1.aiSubdivType" 2;
setAttr "pCube1.inheritsTransform" 1;
pause -sec 1;
arnoldRenderView -option "Wait Render"  "1";

$img = `pwd`;
$img += "/testrender_3.tif";
arnoldRenderView -option "Save Image" $img;


