file -f -o "test.ma";
arnoldRenderView;
pause -sec 3;
arnoldRenderView -option "WaitRender"  "1";
string $imgA = `pwd`;
$imgA += "/testrender.tif";
arnoldRenderView -option "Save Image" $imgA;

arnoldRenderView -option "Color Management.Gamma" "2.1";
arnoldRenderView -option "Display Settings" "0";
arnoldRenderView -option "Color Management.Exposure" "0.7";
arnoldRenderView -option "Display Settings" "1";
arnoldRenderView -option "Color Management.View Transform" "Log";
string $imgB = `pwd`;
$imgB += "/testrender_CM.tif";
arnoldRenderView -option "Save Image" $imgB;

arnoldRenderView -option "Background.Color" "0.8 0.2 0.4";
string $imgC = `pwd`;
$imgC += "/testrender_BG_color.tif";
arnoldRenderView -option "Save Image" $imgC;

arnoldRenderView -option "Background.BG" "BG Image";
string $bgImg = `pwd`;
$bgImg += "/texture1.png";
arnoldRenderView -option "Background.Image" $bgImg;
string $imgD = `pwd`;
$imgD += "/testrender_BG_img.tif";
arnoldRenderView -option "Save Image" $imgD;

arnoldRenderView -option "Background.Scale" "2 1.3";
arnoldRenderView -option "Background.Offset" "0.5 -0.3";
arnoldRenderView -option "Background.Offset" "0.5 -0.3";
arnoldRenderView -option "Background.Apply Color Management" "0";
string $imgE = `pwd`;
$imgE += "/testrender_BG_img2.tif";
arnoldRenderView -option "Save Image" $imgE;


arnoldRenderView -option "Foreground.Enable FG" "1";
string $fgImg = `pwd`;
$fgImg += "/texture_with_alpha.png";

arnoldRenderView -option "Foreground.Image" $fgImg;
arnoldRenderView -option "Foreground.Scale" "0.5 0.6";
string $imgF = `pwd`;
$imgF += "/testrender_FG_img.tif";
arnoldRenderView -option "Save Image" $imgF;

arnoldRenderView -option "Foreground.Offset" "-0.1 -0.1";
arnoldRenderView -option "Foreground.Apply Color Management" "0";
string $imgG = `pwd`;
$imgG += "/testrender_FG_img2.tif";
arnoldRenderView -option "Save Image" $imgG;

quit -force -abort;
