
#include "display_gl.h"

#include <ai.h>

#ifndef _WIN32
#include <dlfcn.h>
#endif

#include <iostream>

/* Print OpenGL error messages */

void GL_print_error(const char *operation)
{
   GLenum error = glGetError();
   switch (error)
   {
      case GL_NO_ERROR:
         // everything fine!
         break;
      case GL_INVALID_ENUM:
         AiMsgWarning("[OpenGL] %s: invalid enum", operation);
         break;
      case GL_INVALID_VALUE:
         AiMsgWarning("[OpenGL] %s: invalid value", operation);
         break;
      case GL_INVALID_OPERATION:
         AiMsgWarning("[OpenGL] %s: invalid operation", operation);
         break;
      case GL_OUT_OF_MEMORY:
         AiMsgWarning("[OpenGL] %s: out of memory", operation);
         break;
      case GL_STACK_UNDERFLOW:
         AiMsgWarning("[OpenGL] %s: stack underflow", operation);
         break;
      case GL_STACK_OVERFLOW:
         AiMsgWarning("[OpenGL] %s: stack overflow", operation);
         break;
      default:
         AiMsgWarning("[OpenGL] %s: unrecognized error (%d)", operation, error);
   }
   return;
}



/* debugging aid */
static void printGPUVariable(const char *name, GLenum type)
{
   const unsigned char err_mark[4] = {0xff, 0xff, 0xff, 0xff};
   float value[32];
   int a;

   memset(value, 0xff, sizeof(value));
   glGetFloatv(type, value);

   std::cerr<<name<<" : ";

   for (a = 0; a < 32; a++) 
   {
      if (memcmp(&value[a], err_mark, sizeof(value[a])) == 0) break;
      std::cerr<<value[a]<<" ";
   }

   std::cerr<<std::endl;
}

void printGPUState(void)
{
   printGPUVariable("GL_ACCUM_ALPHA_BITS", GL_ACCUM_ALPHA_BITS);
   printGPUVariable("GL_ACCUM_BLUE_BITS", GL_ACCUM_BLUE_BITS);
   printGPUVariable("GL_ACCUM_CLEAR_VALUE", GL_ACCUM_CLEAR_VALUE);
   printGPUVariable("GL_ACCUM_GREEN_BITS", GL_ACCUM_GREEN_BITS);
   printGPUVariable("GL_ACCUM_RED_BITS", GL_ACCUM_RED_BITS);
   printGPUVariable("GL_ALPHA_BIAS", GL_ALPHA_BIAS);
   printGPUVariable("GL_ALPHA_BITS", GL_ALPHA_BITS);
   printGPUVariable("GL_ALPHA_SCALE", GL_ALPHA_SCALE);
   printGPUVariable("GL_ALPHA_TEST", GL_ALPHA_TEST);
   printGPUVariable("GL_ALPHA_TEST_FUNC", GL_ALPHA_TEST_FUNC);
   printGPUVariable("GL_ALPHA_TEST_REF", GL_ALPHA_TEST_REF);
   printGPUVariable("GL_ATTRIB_STACK_DEPTH", GL_ATTRIB_STACK_DEPTH);
   printGPUVariable("GL_AUTO_NORMAL", GL_AUTO_NORMAL);
   printGPUVariable("GL_AUX_BUFFERS", GL_AUX_BUFFERS);
   printGPUVariable("GL_BLEND", GL_BLEND);
   printGPUVariable("GL_BLUE_BIAS", GL_BLUE_BIAS);
   printGPUVariable("GL_BLUE_BITS", GL_BLUE_BITS);
   printGPUVariable("GL_BLUE_SCALE", GL_BLUE_SCALE);
   printGPUVariable("GL_CLIENT_ATTRIB_STACK_DEPTH", GL_CLIENT_ATTRIB_STACK_DEPTH);
   printGPUVariable("GL_CLIP_PLANE0", GL_CLIP_PLANE0);
   printGPUVariable("GL_COLOR_ARRAY", GL_COLOR_ARRAY);
   printGPUVariable("GL_COLOR_ARRAY_SIZE", GL_COLOR_ARRAY_SIZE);
   printGPUVariable("GL_COLOR_ARRAY_STRIDE", GL_COLOR_ARRAY_STRIDE);
   printGPUVariable("GL_COLOR_ARRAY_TYPE", GL_COLOR_ARRAY_TYPE);
   printGPUVariable("GL_COLOR_CLEAR_VALUE", GL_COLOR_CLEAR_VALUE);
   printGPUVariable("GL_COLOR_LOGIC_OP", GL_COLOR_LOGIC_OP);
   printGPUVariable("GL_COLOR_MATERIAL", GL_COLOR_MATERIAL);
   printGPUVariable("GL_COLOR_MATERIAL_FACE", GL_COLOR_MATERIAL_FACE);
   printGPUVariable("GL_COLOR_MATERIAL_PARAMETER", GL_COLOR_MATERIAL_PARAMETER);
   printGPUVariable("GL_COLOR_WRITEMASK", GL_COLOR_WRITEMASK);
   printGPUVariable("GL_CULL_FACE", GL_CULL_FACE);
   printGPUVariable("GL_CULL_FACE_MODE", GL_CULL_FACE_MODE);
   printGPUVariable("GL_CURRENT_COLOR", GL_CURRENT_COLOR);
   printGPUVariable("GL_CURRENT_INDEX", GL_CURRENT_INDEX);
   printGPUVariable("GL_CURRENT_NORMAL", GL_CURRENT_NORMAL);
   printGPUVariable("GL_CURRENT_RASTER_COLOR", GL_CURRENT_RASTER_COLOR);
   printGPUVariable("GL_CURRENT_RASTER_DISTANCE", GL_CURRENT_RASTER_DISTANCE);
   printGPUVariable("GL_CURRENT_RASTER_INDEX", GL_CURRENT_RASTER_INDEX);
   printGPUVariable("GL_CURRENT_RASTER_POSITION", GL_CURRENT_RASTER_POSITION);
   printGPUVariable("GL_CURRENT_RASTER_POSITION_VALID", GL_CURRENT_RASTER_POSITION_VALID);
   printGPUVariable("GL_CURRENT_RASTER_TEXTURE_COORDS", GL_CURRENT_RASTER_TEXTURE_COORDS);
   printGPUVariable("GL_CURRENT_TEXTURE_COORDS", GL_CURRENT_TEXTURE_COORDS);
   printGPUVariable("GL_DEPTH_BIAS", GL_DEPTH_BIAS);
   printGPUVariable("GL_DEPTH_BITS", GL_DEPTH_BITS);
   printGPUVariable("GL_DEPTH_CLEAR_VALUE", GL_DEPTH_CLEAR_VALUE);
   printGPUVariable("GL_DEPTH_FUNC", GL_DEPTH_FUNC);
   printGPUVariable("GL_DEPTH_RANGE", GL_DEPTH_RANGE);
   printGPUVariable("GL_DEPTH_SCALE", GL_DEPTH_SCALE);
   printGPUVariable("GL_DEPTH_TEST", GL_DEPTH_TEST);
   printGPUVariable("GL_DEPTH_WRITEMASK", GL_DEPTH_WRITEMASK);
   printGPUVariable("GL_DITHER", GL_DITHER);
   printGPUVariable("GL_DOUBLEBUFFER", GL_DOUBLEBUFFER);
   printGPUVariable("GL_DRAW_BUFFER", GL_DRAW_BUFFER);
   printGPUVariable("GL_EDGE_FLAG", GL_EDGE_FLAG);
   printGPUVariable("GL_EDGE_FLAG_ARRAY", GL_EDGE_FLAG_ARRAY);
   printGPUVariable("GL_EDGE_FLAG_ARRAY_STRIDE", GL_EDGE_FLAG_ARRAY_STRIDE);
   printGPUVariable("GL_FEEDBACK_BUFFER_SIZE", GL_FEEDBACK_BUFFER_SIZE);
   printGPUVariable("GL_FEEDBACK_BUFFER_TYPE", GL_FEEDBACK_BUFFER_TYPE);
   printGPUVariable("GL_FOG", GL_FOG);
   printGPUVariable("GL_FOG_COLOR", GL_FOG_COLOR);
   printGPUVariable("GL_FOG_DENSITY", GL_FOG_DENSITY);
   printGPUVariable("GL_FOG_END", GL_FOG_END);
   printGPUVariable("GL_FOG_HINT", GL_FOG_HINT);
   printGPUVariable("GL_FOG_INDEX", GL_FOG_INDEX);
   printGPUVariable("GL_FOG_MODE", GL_FOG_MODE);
   printGPUVariable("GL_FOG_START", GL_FOG_START);
   printGPUVariable("GL_FRONT_FACE", GL_FRONT_FACE);
   printGPUVariable("GL_GREEN_BIAS", GL_GREEN_BIAS);
   printGPUVariable("GL_GREEN_BITS", GL_GREEN_BITS);
   printGPUVariable("GL_GREEN_SCALE", GL_GREEN_SCALE);
   printGPUVariable("GL_INDEX_ARRAY", GL_INDEX_ARRAY);
   printGPUVariable("GL_INDEX_ARRAY_STRIDE", GL_INDEX_ARRAY_STRIDE);
   printGPUVariable("GL_INDEX_ARRAY_TYPE", GL_INDEX_ARRAY_TYPE);
   printGPUVariable("GL_INDEX_BITS", GL_INDEX_BITS);
   printGPUVariable("GL_INDEX_CLEAR_VALUE", GL_INDEX_CLEAR_VALUE);
   printGPUVariable("GL_INDEX_LOGIC_OP", GL_INDEX_LOGIC_OP);
   printGPUVariable("GL_INDEX_MODE", GL_INDEX_MODE);
   printGPUVariable("GL_INDEX_OFFSET", GL_INDEX_OFFSET);
   printGPUVariable("GL_INDEX_SHIFT", GL_INDEX_SHIFT);
   printGPUVariable("GL_INDEX_WRITEMASK", GL_INDEX_WRITEMASK);
   printGPUVariable("GL_LIGHT0", GL_LIGHT0);
   printGPUVariable("GL_LIGHTING", GL_LIGHTING);
   printGPUVariable("GL_LIGHT_MODEL_AMBIENT", GL_LIGHT_MODEL_AMBIENT);
   printGPUVariable("GL_LIGHT_MODEL_LOCAL_VIEWER", GL_LIGHT_MODEL_LOCAL_VIEWER);
   printGPUVariable("GL_LIGHT_MODEL_TWO_SIDE", GL_LIGHT_MODEL_TWO_SIDE);
   printGPUVariable("GL_LINE_SMOOTH", GL_LINE_SMOOTH);
   printGPUVariable("GL_LINE_SMOOTH_HINT", GL_LINE_SMOOTH_HINT);
   printGPUVariable("GL_LINE_STIPPLE", GL_LINE_STIPPLE);
   printGPUVariable("GL_LINE_STIPPLE_PATTERN", GL_LINE_STIPPLE_PATTERN);
   printGPUVariable("GL_LINE_STIPPLE_REPEAT", GL_LINE_STIPPLE_REPEAT);
   printGPUVariable("GL_LINE_WIDTH", GL_LINE_WIDTH);
   printGPUVariable("GL_LINE_WIDTH_GRANULARITY", GL_LINE_WIDTH_GRANULARITY);
   printGPUVariable("GL_LINE_WIDTH_RANGE", GL_LINE_WIDTH_RANGE);
   printGPUVariable("GL_LIST_BASE", GL_LIST_BASE);
   printGPUVariable("GL_LIST_INDEX", GL_LIST_INDEX);
   printGPUVariable("GL_LIST_MODE", GL_LIST_MODE);
   printGPUVariable("GL_LOGIC_OP_MODE", GL_LOGIC_OP_MODE);
   printGPUVariable("GL_MAP1_COLOR_4", GL_MAP1_COLOR_4);
   printGPUVariable("GL_MAP1_GRID_DOMAIN", GL_MAP1_GRID_DOMAIN);
   printGPUVariable("GL_MAP1_GRID_SEGMENTS", GL_MAP1_GRID_SEGMENTS);
   printGPUVariable("GL_MAP1_INDEX", GL_MAP1_INDEX);
   printGPUVariable("GL_MAP1_NORMAL", GL_MAP1_NORMAL);
   printGPUVariable("GL_MAP1_TEXTURE_COORD_1", GL_MAP1_TEXTURE_COORD_1);
   printGPUVariable("GL_MAP1_TEXTURE_COORD_2", GL_MAP1_TEXTURE_COORD_2);
   printGPUVariable("GL_MAP1_TEXTURE_COORD_3", GL_MAP1_TEXTURE_COORD_3);
   printGPUVariable("GL_MAP1_TEXTURE_COORD_4", GL_MAP1_TEXTURE_COORD_4);
   printGPUVariable("GL_MAP1_VERTEX_3", GL_MAP1_VERTEX_3);
   printGPUVariable("GL_MAP1_VERTEX_4", GL_MAP1_VERTEX_4);
   printGPUVariable("GL_MAP2_COLOR_4", GL_MAP2_COLOR_4);
   printGPUVariable("GL_MAP2_GRID_DOMAIN", GL_MAP2_GRID_DOMAIN);
   printGPUVariable("GL_MAP2_GRID_SEGMENTS", GL_MAP2_GRID_SEGMENTS);
   printGPUVariable("GL_MAP2_INDEX", GL_MAP2_INDEX);
   printGPUVariable("GL_MAP2_NORMAL", GL_MAP2_NORMAL);
   printGPUVariable("GL_MAP2_TEXTURE_COORD_1", GL_MAP2_TEXTURE_COORD_1);
   printGPUVariable("GL_MAP2_TEXTURE_COORD_2", GL_MAP2_TEXTURE_COORD_2);
   printGPUVariable("GL_MAP2_TEXTURE_COORD_3", GL_MAP2_TEXTURE_COORD_3);
   printGPUVariable("GL_MAP2_TEXTURE_COORD_4", GL_MAP2_TEXTURE_COORD_4);
   printGPUVariable("GL_MAP2_VERTEX_3", GL_MAP2_VERTEX_3);
   printGPUVariable("GL_MAP2_VERTEX_4", GL_MAP2_VERTEX_4);
   printGPUVariable("GL_MAP_COLOR", GL_MAP_COLOR);
   printGPUVariable("GL_MAP_STENCIL", GL_MAP_STENCIL);
   printGPUVariable("GL_MATRIX_MODE", GL_MATRIX_MODE);
   printGPUVariable("GL_MAX_CLIENT_ATTRIB_STACK_DEPTH", GL_MAX_CLIENT_ATTRIB_STACK_DEPTH);
   printGPUVariable("GL_MAX_ATTRIB_STACK_DEPTH", GL_MAX_ATTRIB_STACK_DEPTH);
   printGPUVariable("GL_MAX_CLIP_PLANES", GL_MAX_CLIP_PLANES);
   printGPUVariable("GL_MAX_EVAL_ORDER", GL_MAX_EVAL_ORDER);
   printGPUVariable("GL_MAX_LIGHTS", GL_MAX_LIGHTS);
   printGPUVariable("GL_MAX_LIST_NESTING", GL_MAX_LIST_NESTING);
   printGPUVariable("GL_MAX_MODELVIEW_STACK_DEPTH", GL_MAX_MODELVIEW_STACK_DEPTH);
   printGPUVariable("GL_MAX_NAME_STACK_DEPTH", GL_MAX_NAME_STACK_DEPTH);
   printGPUVariable("GL_MAX_PIXEL_MAP_TABLE", GL_MAX_PIXEL_MAP_TABLE);
   printGPUVariable("GL_MAX_PROJECTION_STACK_DEPTH", GL_MAX_PROJECTION_STACK_DEPTH);
   printGPUVariable("GL_MAX_TEXTURE_SIZE", GL_MAX_TEXTURE_SIZE);
   printGPUVariable("GL_MAX_TEXTURE_STACK_DEPTH", GL_MAX_TEXTURE_STACK_DEPTH);
   printGPUVariable("GL_MAX_VIEWPORT_DIMS", GL_MAX_VIEWPORT_DIMS);
   printGPUVariable("GL_MODELVIEW_MATRIX", GL_MODELVIEW_MATRIX);
   printGPUVariable("GL_MODELVIEW_STACK_DEPTH", GL_MODELVIEW_STACK_DEPTH);
   printGPUVariable("GL_NAME_STACK_DEPTH", GL_NAME_STACK_DEPTH);
   printGPUVariable("GL_NORMAL_ARRAY", GL_NORMAL_ARRAY);
   printGPUVariable("GL_NORMAL_ARRAY_STRIDE", GL_NORMAL_ARRAY_STRIDE);
   printGPUVariable("GL_NORMAL_ARRAY_TYPE", GL_NORMAL_ARRAY_TYPE);
   printGPUVariable("GL_NORMALIZE", GL_NORMALIZE);
   printGPUVariable("GL_PACK_ALIGNMENT", GL_PACK_ALIGNMENT);
   printGPUVariable("GL_PACK_LSB_FIRST", GL_PACK_LSB_FIRST);
   printGPUVariable("GL_PACK_ROW_LENGTH", GL_PACK_ROW_LENGTH);
   printGPUVariable("GL_PACK_SKIP_PIXELS", GL_PACK_SKIP_PIXELS);
   printGPUVariable("GL_PACK_SKIP_ROWS", GL_PACK_SKIP_ROWS);
   printGPUVariable("GL_PACK_SWAP_BYTES", GL_PACK_SWAP_BYTES);
   printGPUVariable("GL_PERSPECTIVE_CORRECTION_HINT", GL_PERSPECTIVE_CORRECTION_HINT);
   printGPUVariable("GL_PIXEL_MAP_A_TO_A_SIZE", GL_PIXEL_MAP_A_TO_A_SIZE);
   printGPUVariable("GL_PIXEL_MAP_B_TO_B_SIZE", GL_PIXEL_MAP_B_TO_B_SIZE);
   printGPUVariable("GL_PIXEL_MAP_G_TO_G_SIZE", GL_PIXEL_MAP_G_TO_G_SIZE);
   printGPUVariable("GL_PIXEL_MAP_I_TO_A_SIZE", GL_PIXEL_MAP_I_TO_A_SIZE);
   printGPUVariable("GL_PIXEL_MAP_I_TO_B_SIZE", GL_PIXEL_MAP_I_TO_B_SIZE);
   printGPUVariable("GL_PIXEL_MAP_I_TO_G_SIZE", GL_PIXEL_MAP_I_TO_G_SIZE);
   printGPUVariable("GL_PIXEL_MAP_I_TO_I_SIZE", GL_PIXEL_MAP_I_TO_I_SIZE);
   printGPUVariable("GL_PIXEL_MAP_I_TO_R_SIZE", GL_PIXEL_MAP_I_TO_R_SIZE);
   printGPUVariable("GL_PIXEL_MAP_R_TO_R_SIZE", GL_PIXEL_MAP_R_TO_R_SIZE);
   printGPUVariable("GL_PIXEL_MAP_S_TO_S_SIZE", GL_PIXEL_MAP_S_TO_S_SIZE);
   printGPUVariable("GL_POINT_SIZE", GL_POINT_SIZE);
   printGPUVariable("GL_POINT_SIZE_GRANULARITY", GL_POINT_SIZE_GRANULARITY);
   printGPUVariable("GL_POINT_SIZE_RANGE", GL_POINT_SIZE_RANGE);
   printGPUVariable("GL_POINT_SMOOTH", GL_POINT_SMOOTH);
   printGPUVariable("GL_POINT_SMOOTH_HINT", GL_POINT_SMOOTH_HINT);
   printGPUVariable("GL_POLYGON_MODE", GL_POLYGON_MODE);
   printGPUVariable("GL_POLYGON_OFFSET_FACTOR", GL_POLYGON_OFFSET_FACTOR);
   printGPUVariable("GL_POLYGON_OFFSET_UNITS", GL_POLYGON_OFFSET_UNITS);
   printGPUVariable("GL_POLYGON_OFFSET_FILL", GL_POLYGON_OFFSET_FILL);
   printGPUVariable("GL_POLYGON_OFFSET_LINE", GL_POLYGON_OFFSET_LINE);
   printGPUVariable("GL_POLYGON_OFFSET_POINT", GL_POLYGON_OFFSET_POINT);
   printGPUVariable("GL_POLYGON_SMOOTH", GL_POLYGON_SMOOTH);
   printGPUVariable("GL_POLYGON_SMOOTH_HINT", GL_POLYGON_SMOOTH_HINT);
   printGPUVariable("GL_POLYGON_STIPPLE", GL_POLYGON_STIPPLE);
   printGPUVariable("GL_PROJECTION_MATRIX", GL_PROJECTION_MATRIX);
   printGPUVariable("GL_PROJECTION_STACK_DEPTH", GL_PROJECTION_STACK_DEPTH);
   printGPUVariable("GL_READ_BUFFER", GL_READ_BUFFER);
   printGPUVariable("GL_RED_BIAS", GL_RED_BIAS);
   printGPUVariable("GL_RED_BITS", GL_RED_BITS);
   printGPUVariable("GL_RED_SCALE", GL_RED_SCALE);
   printGPUVariable("GL_RENDER_MODE", GL_RENDER_MODE);
   printGPUVariable("GL_RGBA_MODE", GL_RGBA_MODE);
   printGPUVariable("GL_SCISSOR_BOX", GL_SCISSOR_BOX);
   printGPUVariable("GL_SCISSOR_TEST", GL_SCISSOR_TEST);
   printGPUVariable("GL_SELECTION_BUFFER_SIZE", GL_SELECTION_BUFFER_SIZE);
   printGPUVariable("GL_SHADE_MODEL", GL_SHADE_MODEL);
   printGPUVariable("GL_STENCIL_BITS", GL_STENCIL_BITS);
   printGPUVariable("GL_STENCIL_CLEAR_VALUE", GL_STENCIL_CLEAR_VALUE);
   printGPUVariable("GL_STENCIL_FAIL", GL_STENCIL_FAIL);
   printGPUVariable("GL_STENCIL_FUNC", GL_STENCIL_FUNC);
   printGPUVariable("GL_STENCIL_PASS_DEPTH_FAIL", GL_STENCIL_PASS_DEPTH_FAIL);
   printGPUVariable("GL_STENCIL_PASS_DEPTH_PASS", GL_STENCIL_PASS_DEPTH_PASS);
   printGPUVariable("GL_STENCIL_REF", GL_STENCIL_REF);
   printGPUVariable("GL_STENCIL_TEST", GL_STENCIL_TEST);
   printGPUVariable("GL_STENCIL_VALUE_MASK", GL_STENCIL_VALUE_MASK);
   printGPUVariable("GL_STENCIL_WRITEMASK", GL_STENCIL_WRITEMASK);
   printGPUVariable("GL_STEREO", GL_STEREO);
   printGPUVariable("GL_SUBPIXEL_BITS", GL_SUBPIXEL_BITS);
   printGPUVariable("GL_TEXTURE_1D", GL_TEXTURE_1D);
   printGPUVariable("GL_TEXTURE_BINDING_1D", GL_TEXTURE_BINDING_1D);
   printGPUVariable("GL_TEXTURE_2D", GL_TEXTURE_2D);
   printGPUVariable("GL_TEXTURE_BINDING_2D", GL_TEXTURE_BINDING_2D);
   printGPUVariable("GL_TEXTURE_COORD_ARRAY", GL_TEXTURE_COORD_ARRAY);
   printGPUVariable("GL_TEXTURE_COORD_ARRAY_SIZE", GL_TEXTURE_COORD_ARRAY_SIZE);
   printGPUVariable("GL_TEXTURE_COORD_ARRAY_STRIDE", GL_TEXTURE_COORD_ARRAY_STRIDE);
   printGPUVariable("GL_TEXTURE_COORD_ARRAY_TYPE", GL_TEXTURE_COORD_ARRAY_TYPE);
   printGPUVariable("GL_TEXTURE_GEN_Q", GL_TEXTURE_GEN_Q);
   printGPUVariable("GL_TEXTURE_GEN_R", GL_TEXTURE_GEN_R);
   printGPUVariable("GL_TEXTURE_GEN_S", GL_TEXTURE_GEN_S);
   printGPUVariable("GL_TEXTURE_GEN_T", GL_TEXTURE_GEN_T);
   printGPUVariable("GL_TEXTURE_MATRIX", GL_TEXTURE_MATRIX);
   printGPUVariable("GL_TEXTURE_STACK_DEPTH", GL_TEXTURE_STACK_DEPTH);
   printGPUVariable("GL_UNPACK_ALIGNMENT", GL_UNPACK_ALIGNMENT);
   printGPUVariable("GL_UNPACK_LSB_FIRST", GL_UNPACK_LSB_FIRST);
   printGPUVariable("GL_UNPACK_ROW_LENGTH", GL_UNPACK_ROW_LENGTH);
   printGPUVariable("GL_UNPACK_SKIP_PIXELS", GL_UNPACK_SKIP_PIXELS);
   printGPUVariable("GL_UNPACK_SKIP_ROWS", GL_UNPACK_SKIP_ROWS);
   printGPUVariable("GL_UNPACK_SWAP_BYTES", GL_UNPACK_SWAP_BYTES);
   printGPUVariable("GL_VERTEX_ARRAY", GL_VERTEX_ARRAY);
   printGPUVariable("GL_VERTEX_ARRAY_SIZE", GL_VERTEX_ARRAY_SIZE);
   printGPUVariable("GL_VERTEX_ARRAY_STRIDE", GL_VERTEX_ARRAY_STRIDE);
   printGPUVariable("GL_VERTEX_ARRAY_TYPE", GL_VERTEX_ARRAY_TYPE);
   printGPUVariable("GL_VIEWPORT", GL_VIEWPORT);
   printGPUVariable("GL_ZOOM_X", GL_ZOOM_X);
   printGPUVariable("GL_ZOOM_Y", GL_ZOOM_Y);
}


