setAttr "defaultArnoldRenderOptions.log_verbosity" 3;
arnoldRenderView -mode "render_silent";
pause -sec 1;

arnoldRenderView -mode "render_silent";
pause -sec 1;

string $img = `pwd`;
$img += "/testrender_1.tif";
print ("----- render 1 = "+$img+"\n");
arnoldRenderView -option "Save Image" $img;

string $preMel = "print \"PRE RENDER\\n\";setAttr \"polySphere1.radius\" 2.0;\nsetAttr \"lambert1.color\" 0.4 0.9 0.1;";
setAttr "defaultRenderGlobals.preMel" -type "string" $preMel;

arnoldRenderView -mode "render_silent";
pause -sec 1;

$img = `pwd`;
$img += "/testrender_2.tif";
print ("----- render 2 = "+$img+"\n");
arnoldRenderView -option "Save Image" $img;

