global proc SetupArnoldGlobalsTabs()
{
   createNode -skipSelect -shared -n "defaultArnoldRenderOptions" ArnoldRenderOptions;
   
   renderer -edit arnold -addGlobalsTab "Common" "createMayaSoftwareCommonGlobalsTab" "updateMayaSoftwareCommonGlobalsTab";
   renderer -edit arnold -addGlobalsTab "Arnold Renderer" "CreateArnoldRendererGlobalsTab" "UpdateArnoldRendererGlobalsTab";
   renderer -edit arnold -addGlobalsNode "defaultArnoldRenderOptions";
}