# vim: filetype=python

import system, os
from build_tools import find_files_recursive

# import build env
Import('ext_env')
local_env = ext_env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'contrib', 'extensions', 'synColor', 'plugin')

source_files  = [os.path.join('plugin', x) for x in find_files_recursive(src_base_dir, ['.c', '.cpp'])]
include_files = [os.path.join('plugin', x) for x in find_files_recursive(src_base_dir, ['.h'])]

EXT = local_env.SharedLibrary('synColor_plugins', source_files, LIBPREFIX='')

if system.os() == 'windows':
   local_env['MSVSSCONSCRIPT'] = local_env.File('SConscript')   
   local_env.Append(CPPPATH = ['.'])
else:
   local_env.Append(CPPPATH = ['.'])


# import build env
Import('env')
shader_env = env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(shader_env['ROOT_DIR'], 'contrib', 'extensions', 'synColor', 'shaders')
source_files  = [os.path.join('shaders', x) for x in find_files_recursive(src_base_dir, ['.c', '.cpp'])]
include_files = [os.path.join('shaders', x) for x in find_files_recursive(src_base_dir, ['.h'])]

shader_env.Append(CPPPATH = ['.'])
if system.os() =='windows':
   shader_env.Append(LIBS=Split('ai.lib'))
   shader_env.Append(LIBS=Split('staticSynColor.lib expat_vc11.lib Half.lib IccProfLib_vc11.lib Iex-2_2.lib IexMath-2_2.lib'))
   shader_env.Append(LIBS=Split('Ilmthread-2_2.lib Imath-2_2.lib libyaml-cppmd.lib OpenColorIO.lib tinyxml.lib tinyxpath_vc11.lib'))
   shader_env.Append(LIBS=Split('libboost_filesystem.lib libboost_system.lib'))
   shader_env.Append(CPPPATH = [os.path.join(shader_env['ROOT_DIR'], 'external', 'synColorStatic', 'include')])
   shader_env.Append(LIBPATH = [os.path.join(shader_env['ROOT_DIR'], 'external', 'synColorStatic', 'lib')])
   shader_env.Append(CPPDEFINES = Split('SYN_LINK_STATIC'))
else:
   shader_env.Append(LIBS=Split('ai'))
   shader_env.Append(CCFLAGS = Split('-fvisibility=hidden')) # hide symbols by default
   shader_env.Append(CPPPATH = [os.path.join(shader_env['ROOT_DIR'], 'external', 'synColor', 'include')])
   if system.os() =='darwin':
      shader_env.Append(LIBPATH = [os.path.join(shader_env['ROOT_DIR'], 'external', 'synColor', 'lib', 'darwin')])
   else:
      shader_env.Append(LIBPATH = [os.path.join(shader_env['ROOT_DIR'], 'external', 'synColor', 'lib', 'linux')])

EXT_SHADERS = shader_env.SharedLibrary('synColor_shaders', source_files, LIBPREFIX='')

if system.os() == 'windows':
   shader_env['MSVSSCONSCRIPT'] = shader_env.File('SConscript')

Return('EXT EXT_SHADERS')
