# vim: filetype=python

# SConscript file for tiff2jpeg

import system

import os

# add all source files here
source_files = ['tiff2jpeg.c',]

####################################################################
# you probably don't want to mess below this line...
####################################################################

# import build env
Import('env')
local_env = env.Clone()

# Obtain the name of the target architecture
arch = system.get_arch_label(system.os(), system.target_arch())

## attach 3rd party libs
local_env.Append(CPPPATH = [os.path.join(env['EXTERNAL_PATH'], 'tiff-3.8.2', 'dist', 'include')])
local_env.Append(CPPPATH = [os.path.join(env['EXTERNAL_PATH'], 'jpeg-6b', 'dist', 'include', arch)])
local_env.Append(LIBPATH = [os.path.join(env['EXTERNAL_PATH'], 'tiff-3.8.2', 'dist', 'lib', arch)])
local_env.Append(LIBPATH = [os.path.join(env['EXTERNAL_PATH'], 'jpeg-6b', 'dist', 'lib', arch)])
local_env.Append(LIBS = Split('libtiff jpeglib'))

# make Program (.bin, .app, .exe, etc) with env
TIFF2JPEG = local_env.Program('tiff2jpeg', source_files)

# hand back result
Return('TIFF2JPEG')
