# vim: filetype=python

import utils.system as system
import os
from utils.build_tools import find_files_recursive

# import build env
Import('ext_env')
local_env = ext_env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(local_env['ROOT_DIR'], 'contrib', 'extensions', 'renderSetup', 'plugin')

source_files  = [os.path.join('plugin', x) for x in find_files_recursive(src_base_dir, ['.c', '.cpp'])]
include_files = [os.path.join('plugin', x) for x in find_files_recursive(src_base_dir, ['.h'])]

EXT = local_env.SharedLibrary('renderSetup', source_files, LIBPREFIX='')

if system.os == 'windows':
   local_env['MSVSSCONSCRIPT'] = local_env.File('SConscript')   
   local_env.Append(CPPPATH = ['.'])
else:
   local_env.Append(CPPPATH = ['.'])


# import build env
Import('env')
shader_env = env.Clone()

# Automatically add all source and include files found in the source path
src_base_dir  = os.path.join(shader_env['ROOT_DIR'], 'contrib', 'extensions', 'renderSetup', 'shaders')
source_files  = [os.path.join('shaders', x) for x in find_files_recursive(src_base_dir, ['.c', '.cpp'])]
include_files = [os.path.join('shaders', x) for x in find_files_recursive(src_base_dir, ['.h'])]

if system.os =='windows':
   shader_env.Append(CPPPATH = ['.'])
   shader_env.Append(CPPPATH = [os.path.join(shader_env['ROOT_DIR'], 'contrib', 'extensions', 'renderSetup', 'common')])
   shader_env.Append(LIBS=Split('ai.lib'))
else:
   shader_env.Append(CPPPATH = ['.'])
   shader_env.Append(CPPPATH = [os.path.join(shader_env['ROOT_DIR'], 'contrib', 'extensions', 'renderSetup', 'common')])
   shader_env.Append(LIBS=Split('ai'))
   shader_env.Append(CCFLAGS = Split('-fvisibility=hidden')) # hide symbols by default


EXT_SHADERS = shader_env.SharedLibrary('renderSetup_shaders', source_files, LIBPREFIX='')

if system.os == 'windows':
   shader_env['MSVSSCONSCRIPT'] = shader_env.File('SConscript')

Return('EXT EXT_SHADERS')
